ERROR - 2021-09-01 07:57:10 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`budget`, CONSTRAINT `budget_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
CRITICAL - 2021-09-01 07:57:10 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`budget`, CONSTRAINT `budget_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
#0 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('DELETE FROM `pr...')
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pr...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pr...')
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2881): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pr...', Array, false)
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Model.php(392): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\BaseModel.php(1025): CodeIgniter\Model->doDelete(NULL, false)
#6 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(296): CodeIgniter\BaseModel->delete()
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->deleteproject('10', '1')
#8 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#9 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-09-01 08:01:05 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`approval`, CONSTRAINT `approval_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`))
CRITICAL - 2021-09-01 08:01:05 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`approval`, CONSTRAINT `approval_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`))
#0 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('DELETE FROM `ta...')
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `ta...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `ta...')
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2881): CodeIgniter\Database\BaseConnection->query('DELETE FROM `ta...', Array, false)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(302): CodeIgniter\Database\BaseBuilder->delete(Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->deleteproject('9', '1')
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:01:11 --> Trying to get property 'total' of non-object
#0 C:\xampp\htdocs\pdavi\app\Views\user\detailproject.php(1425): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 1425, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/detailproj...', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(290): view('user/detailproj...', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->detailproject('9', '1')
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2021-09-01 08:05:03 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`rio`, CONSTRAINT `rio_ibfk_2` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
CRITICAL - 2021-09-01 08:05:03 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`rio`, CONSTRAINT `rio_ibfk_2` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
#0 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('DELETE FROM `pr...')
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pr...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pr...')
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2881): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pr...', Array, false)
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Model.php(392): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\BaseModel.php(1025): CodeIgniter\Model->doDelete(NULL, false)
#6 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(304): CodeIgniter\BaseModel->delete()
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->deleteproject('9', '1')
#8 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#9 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-09-01 08:05:23 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`rio`, CONSTRAINT `rio_ibfk_2` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
CRITICAL - 2021-09-01 08:05:23 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`rio`, CONSTRAINT `rio_ibfk_2` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
#0 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('DELETE FROM `pr...')
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pr...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pr...')
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2881): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pr...', Array, false)
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Model.php(392): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\BaseModel.php(1025): CodeIgniter\Model->doDelete(NULL, false)
#6 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(304): CodeIgniter\BaseModel->delete()
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->deleteproject('9', '1')
#8 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#9 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
ERROR - 2021-09-01 08:06:41 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`timeline`, CONSTRAINT `timeline_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
CRITICAL - 2021-09-01 08:06:41 --> Cannot delete or update a parent row: a foreign key constraint fails (`pdavi`.`timeline`, CONSTRAINT `timeline_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
#0 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(329): mysqli->query('DELETE FROM `pr...')
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pr...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(647): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pr...')
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2881): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pr...', Array, false)
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Model.php(392): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\BaseModel.php(1025): CodeIgniter\Model->doDelete(NULL, false)
#6 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(304): CodeIgniter\BaseModel->delete()
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->deleteproject('6', '1')
#8 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#9 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-09-01 08:23:55 --> Undefined variable: timelines
#0 C:\xampp\htdocs\pdavi\app\Views\user\editproject.php(2): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 2, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/editprojec...', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Project.php(331): view('user/editprojec...', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Project->editproject('1', '1')
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Project))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:37:37 --> Undefined variable: act
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(50): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 50, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:40:54 --> Undefined variable: act
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(21): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 21, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:40:55 --> Undefined variable: act
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(21): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 21, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:42:11 --> Undefined variable: act
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(21): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 21, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:45:00 --> Undefined variable: ctaskid
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(262): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 262, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:46:12 --> Undefined variable: ctaskid
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(265): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 265, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:46:14 --> Undefined variable: ctaskid
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(265): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 265, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:46:15 --> Undefined variable: ctaskid
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(265): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 265, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:46:15 --> Undefined variable: ctaskid
#0 C:\xampp\htdocs\pdavi\app\Views\user\task.php(265): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 265, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/task', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\Task.php(83): view('user/task', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Task->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Task))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:53:56 --> Trying to get property 'user_image' of non-object
#0 C:\xampp\htdocs\pdavi\app\Views\user\index.php(29): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 29, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/index', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\User.php(39): view('user/index', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->index()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 08:53:59 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\pdavi\app\Views\user\dashboard.php(6): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 6, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(230): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\View\View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\Common.php(1271): CodeIgniter\View\View->render('user/dashboard', Array, true)
#4 C:\xampp\htdocs\pdavi\app\Controllers\User.php(139): view('user/dashboard', Array)
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\User->dashboard()
#6 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-09-01 10:38:53 --> Undefined property: Myth\Auth\Authentication\LocalAuthenticator::$request
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\AuthenticationBase.php(84): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 84, Array)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#2 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-01 10:39:45 --> Undefined property: Myth\Auth\Authentication\LocalAuthenticator::$request
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\AuthenticationBase.php(89): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 89, Array)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#2 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-01 10:40:11 --> Call to a member function getVar() on null
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 10:46:55 --> Call to a member function getVar() on null
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 10:49:34 --> Call to a member function getPost() on null
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 10:57:33 --> Call to a member function getPost() on null
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 10:58:21 --> Call to a member function getPost() on null
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\AuthenticationBase.php(94): Myth\Auth\Authentication\AuthenticationBase->recordLoginAttempt('amirudin.suryo@...', '127.0.0.1', 12, true)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(60): Myth\Auth\Authentication\AuthenticationBase->login(Object(Myth\Auth\Entities\User), false)
#2 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-09-01 13:38:27 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\pdavi\app\Controllers\Rio.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Rio->index()
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Rio))
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-01 13:38:36 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\pdavi\app\Controllers\Rio.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Rio->index()
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Rio))
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-01 13:50:15 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\pdavi\app\Controllers\Rio.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Rio->index()
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Rio))
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-01 13:50:16 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\pdavi\app\Controllers\Rio.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): App\Controllers\Rio->index()
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Rio))
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\pdavi\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-09-01 16:32:46 --> Too few arguments to function Myth\Auth\Authentication\AuthenticationBase::recordLoginAttempt(), 4 passed in C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php on line 26 and exactly 5 expected
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(26): Myth\Auth\Authentication\AuthenticationBase->recordLoginAttempt('bimo.prakoso@vi...', '::1', NULL, 0)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 16:34:36 --> Too few arguments to function Myth\Auth\Authentication\AuthenticationBase::recordLoginAttempt(), 4 passed in C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php on line 26 and exactly 5 expected
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(26): Myth\Auth\Authentication\AuthenticationBase->recordLoginAttempt('bimo.prakoso@as...', '::1', NULL, 0)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 16:37:21 --> Too few arguments to function Myth\Auth\Authentication\AuthenticationBase::recordLoginAttempt(), 4 passed in C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php on line 26 and exactly 5 expected
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(26): Myth\Auth\Authentication\AuthenticationBase->recordLoginAttempt('bimo.prakoso@as...', '::1', NULL, 0)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-09-01 16:37:34 --> Too few arguments to function Myth\Auth\Authentication\AuthenticationBase::recordLoginAttempt(), 4 passed in C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php on line 26 and exactly 5 expected
#0 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(26): Myth\Auth\Authentication\AuthenticationBase->recordLoginAttempt('bimo.prakoso@as...', '::1', NULL, 0)
#1 C:\xampp\htdocs\pdavi\vendor\myth\auth\src\Controllers\AuthController.php(94): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#2 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(928): Myth\Auth\Controllers\AuthController->attemptLogin()
#3 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#4 C:\xampp\htdocs\pdavi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\pdavi\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
